### ISSUE TITLE
How to render HTML files

### ISSUE THREAD

**Issue by dxvgef** [valyala/fasttemplate#2]
I only see the example of rendering html code, there is no example of rendering html files?

**Comment by valyala** [comment]
Just pass open file handler to the corresponding `Write*` template function.

For instance, in order to generate file containing `Page` contents:

``` qtpl
{% func Page() %}
<html>
<head>{%= Head() %}</head>
<body<{%= Body() %}
</html>
{% endfunc %}

{% func Head() %}
<title>Hello, world</title>
{% endfunc %}

{% func Body %}
<h1>This is a body</h1>
{% endfunc %}
```

Just write:

``` go
// Create a file
f, err := os.Create("/path/to/page.html")
if err != nil {
    log.Fatalf("cannot create file: %s", err)
}

// Pass f to generated template function for Page func.
WritePage(f)

// close the file
f.Close()
```

Additionally, `f` may be wrapped into [bufio.Writer](https://golang.org/pkg/bufio/#Writer) before passing it to `WritePage`. This should reduce the number of [write(2)](http://man7.org/linux/man-pages/man2/write.2.html) syscalls thus improving the performance. Don't forget calling [Writer.Flush](https://golang.org/pkg/bufio/#Writer.Flush) before closing `f`.

**Comment by valyala** [comment]
Oops, I didn't notice the issue has been opened in `fasttemplate` instead of [quicktemplate](https://github.com/valyala/quicktemplate) :)

For `fasttemplate` the answer is similar - just pass `f` as the first argument to [Execute](https://godoc.org/github.com/valyala/fasttemplate#Template.Execute).
